/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_foiacloud_multifunctionRoute_MappingInterface */

#ifndef _Included_com_rany010_JavaInterface
#define _Included_com_rany010_JavaInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rany010_JavaInterface
 * Method:    testFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rany010_JavaInterface_testFunc
  (JNIEnv *, jobject);

/*
 * Class:     com_rany010_JavaInterface
 * Method:    inputAndOutputString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rany010_JavaInterface_inputAndOutputString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_rany010_JavaInterface
 * Method:    setStruct
 * Signature: (Lcom/rany010/JavaInterface/Params;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rany010_JavaInterface_setStruct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rany010_JavaInterface
 * Method:    getStruct
 * Signature: ()Lcom/rany010/JavaInterface/Params;
 */
JNIEXPORT jobject JNICALL Java_com_rany010_JavaInterface_getStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_rany010_JavaInterface
 * Method:    setListStruct
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rany010_JavaInterface_setListStruct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rany010_JavaInterface
 * Method:    getListStruct
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_rany010_JavaInterface_getListStruct
  (JNIEnv *, jobject);

/*
 * Class:     com_rany010_JavaInterface
 * Method:    setStructList
 * Signature: (Lcom/rany010/JavaInterface/Params;)
 */
JNIEXPORT jboolean JNICALL Java_com_rany010_JavaInterface_setStructList
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
